from enum import StrEnum


class State(StrEnum):
    QUESTION_RECEIVED = "QUESTION_RECEIVED"
    QUESTION_EXPLAINED = "QUESTION_EXPLAINED"
    CONCEPT_HINT = "CONCEPT_HINT"
    STRUCTURAL_HINT = "STRUCTURAL_HINT"
    ERROR_ANALYSIS = "ERROR_ANALYSIS"
    STRONG_HINT = "STRONG_HINT"
    SOLVED = "SOLVED"
    FINAL_SOLUTION = "FINAL_SOLUTION"
    EXPLANATION = "EXPLANATION"
    SIMILAR_PRACTICE = "SIMILAR_PRACTICE"


class Event(StrEnum):
    EXPLAIN_QUESTION = "EXPLAIN_QUESTION"
    REQUEST_HINT = "REQUEST_HINT"
    SUBMIT_ATTEMPT = "SUBMIT_ATTEMPT"
    REQUEST_SOLUTION = "REQUEST_SOLUTION"
    REQUEST_EXPLANATION = "REQUEST_EXPLANATION"
    REQUEST_PRACTICE = "REQUEST_PRACTICE"


class Outcome(StrEnum):
    INDEPENDENT = "independent"
    WITH_HINTS = "with_hints"
    NEEDED_SOLUTION = "needed_solution"
